### ISSUE TITLE
[feature] support google container engine -- GKE

### ISSUE THREAD

**Issue by songbinliu** [turbonomic/kubeturbo#120]
[**Problem**]  
When trying to deploy kubeturbo on GKE kubernetes cluster, there is an error:
```terminal
E1108 20:29:00.927027       1 kubeturbo_builder.go:129] Fatal error: failed to create kubeClient:No Auth Provider found for name "gcp"

```

[**Goal**]
Enable deploy kubeturbo on GKE kubernetes cluster.

**Comment by songbinliu** [comment]
Progress

1. Solve the "gcp" problem by add dependency of [`_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"`] (https://github.com/kubernetes/client-go/issues/242)
 Failed with a new error:
 ```terminal
k8s_discovery_client.go:129] Failed to get all nodes in the cluster: failed to list all nodes in the cluster: Get https://35.196.33.113/api/v1/nodes: error executing access token command "/Users/me/Downloads/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /Users/steven/Downloads/google-cloud-sdk/bin/gcloud: no such file or directory output=
```

2.  Someone suggests use in-cluster settings to generate the kubernetes client, without have to introduce the dependency of `k8s.io/client-go/plugin/pkg/client/auth/gcp`
     
     (1) Able to access k8s API;
     (2) **Unable** to access the metrics from the kubelets.

**Comment by songbinliu** [comment]
According to research, we don't have to change any code for GKE, but we have to change the configuration to deploy Kubeturbo in GKE:  `Use in-cluster settings to generate the Kubernetes client`.

The yaml file of Kubeturbo for GKE is like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo-gke-max
  labels:
    name: kubeturbo
spec:
  nodeSelector:
      kubeturbo: deployable
  containers:
  - name: kubeturbo-60
    image: vmturbo/kubeturbo:6.0 
    imagePullPolicy: Always
    args:
      - --turboconfig=/etc/kubeturbo/turbo24.conf
      - --v=3
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    hostPath:
      path: /home/songbin_liu/kubeturbo/config
```
