### ISSUE TITLE
deploy kubeturbo without access to the node

### ISSUE THREAD

**Issue by songbinliu** [turbonomic/kubeturbo#132]
In some scenarios, we are not able to access the nodes directly, for example, we can only deploy kubeturbo through the Openshift Web UI. There will be two problems:

*Problem1*: not able to place the configuration files
In current deploy guides, we have to ssh into a node, and place on that nodes with two files:
- kubeconfig : to access the kubernetes API;
- turbo.config: to access Turbo server;

*Problem2*: not able to label the node

**Comment by songbinliu** [comment]
One solution is to use configMap.
1. *Get rid of kubeconfig* : for kubernetes 1.6+ and Openshift 3.6+, *Kubeconfig* is not necessary;

2. *Put turbo.config into configMap*:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmt-config
  namespace: default
data:
    turbo.conf: | 
        {"communicationConfig":{"serverMeta":{"version":"6.0.0","turboServer":"https://1.2.3.4"},"restAPIConfig":{"opsManagerUserName":"administrator","opsManagerPassword":"pass"}},"targetConfig":{"probeCategory":"CloudNative","targetType":"Kubernetes","address":"https://openshift.3.7.cluster","username":"kube.user","password":"kube.passwd"} 
---        
apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo
spec:
  nodeSelector:
    kubeturbo: deployable
  containers:
  - name: kubeturbo
    image: vmturbo/kubeturbo:6.0
    args:
      - --turboconfig=/etc/kubeturbo/config
      - --v=3
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    configMap:
      name: vmt-config
```

**Comment by songbinliu** [comment]
If we want to deploy it with `Secret` instead of `Configmap`, we have to encode the content with [`base64`](https://www.base64encode.org), and add the base64 string to the secret.

For example, if the JSON content is:
```json
 {"communicationConfig":{"serverMeta":{"version":"6.0.0","turboServer":"https://1.2.3.4"},"restAPIConfig":{"opsManagerUserName":"administrator","opsManagerPassword":"pass"}},"targetConfig":{"probeCategory":"CloudNative","targetType":"Kubernetes","address":"https://openshift.3.7.cluster","username":"kube.user","password":"kube.passwd"} }
```
After base64 encoding, get:
```console
IHsiY29tbXVuaWNhdGlvbkNvbmZpZyI6eyJzZXJ2ZXJNZXRhIjp7InZlcnNpb24iOiI2LjAuMCIsInR1cmJvU2VydmVyIjoiaHR0cHM6Ly8xLjIuMy40In0sInJlc3RBUElDb25maWciOnsib3BzTWFuYWdlclVzZXJOYW1lIjoiYWRtaW5pc3RyYXRvciIsIm9wc01hbmFnZXJQYXNzd29yZCI6InBhc3MifX0sInRhcmdldENvbmZpZyI6eyJwcm9iZUNhdGVnb3J5IjoiQ2xvdWROYXRpdmUiLCJ0YXJnZXRUeXBlIjoiS3ViZXJuZXRlcyIsImFkZHJlc3MiOiJodHRwczovL29wZW5zaGlmdC4zLjcuY2x1c3RlciIsInVzZXJuYW1lIjoia3ViZS51c2VyIiwicGFzc3dvcmQiOiJrdWJlLnBhc3N3ZCJ9IH0NCg==
```

*1*.  deploy the Secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: turbo-conf
data:
    turbo.conf: IHsiY29tbXVuaWNhdGlvbkNvbmZpZyI6eyJzZXJ2ZXJNZXRhIjp7InZlcnNpb24iOiI2LjAuMCIsInR1cmJvU2VydmVyIjoiaHR0cHM6Ly8xLjIuMy40In0sInJlc3RBUElDb25maWciOnsib3BzTWFuYWdlclVzZXJOYW1lIjoiYWRtaW5pc3RyYXRvciIsIm9wc01hbmFnZXJQYXNzd29yZCI6InBhc3MifX0sInRhcmdldENvbmZpZyI6eyJwcm9iZUNhdGVnb3J5IjoiQ2xvdWROYXRpdmUiLCJ0YXJnZXRUeXBlIjoiS3ViZXJuZXRlcyIsImFkZHJlc3MiOiJodHRwczovL29wZW5zaGlmdC4zLjcuY2x1c3RlciIsInVzZXJuYW1lIjoia3ViZS51c2VyIiwicGFzc3dvcmQiOiJrdWJlLnBhc3N3ZCJ9IH0NCg==
```

*2*.  deploy the Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo-gke
  labels:
    name: kubeturbo
spec:
  containers:
  - name: kubeturbo-6
    image: vmturbo/kubeturbo:6.0
    args:
      - --turboconfig=/etc/kubeturbo/turbo.conf
      - --v=3
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    secret: 
      secretName: turbo-conf  
```
